export enum UserType {
  PATIENT = 'PATIENT',
  NURSE = 'NURSE',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  DELETED = 'DELETED',
}

export enum VerificationStatus {
  INCOMPLETE = 'INCOMPLETE',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum GenderPreference {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NO_PREFERENCE = 'NO_PREFERENCE',
}

export enum BookingStatus {
  PENDING_OFFERS = 'PENDING_OFFERS',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  NURSE_SELECTED = 'NURSE_SELECTED',
  NURSE_CONFIRMED = 'NURSE_CONFIRMED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  VISIT_STARTED = 'VISIT_STARTED',
  VISIT_COMPLETED = 'VISIT_COMPLETED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  RATED = 'RATED',
  CLOSED = 'CLOSED',
  CANCELLED_BY_PATIENT = 'CANCELLED_BY_PATIENT',
  CANCELLED_BY_NURSE = 'CANCELLED_BY_NURSE',
  REASSIGNMENT = 'REASSIGNMENT',
  EXPIRED = 'EXPIRED',
  DISPUTE = 'DISPUTE',
  SCHEDULED_PENDING = 'SCHEDULED_PENDING',
}

export enum RequestType {
  STANDARD = 'STANDARD',
  SOS = 'SOS',
  SCHEDULED = 'SCHEDULED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  FAWRY = 'FAWRY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum OfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum WalletTransactionType {
  CREDIT = 'CREDIT',
  COMMISSION = 'COMMISSION',
  WITHDRAWAL = 'WITHDRAWAL',
  PREPAID_TOPUP = 'PREPAID_TOPUP',
  PREPAID_DEBIT = 'PREPAID_DEBIT',
  REFUND_DEDUCTION = 'REFUND_DEDUCTION',
  DEBT = 'DEBT',
}

export enum DocumentType {
  NATIONAL_ID = 'NATIONAL_ID',
  NURSING_LICENSE = 'NURSING_LICENSE',
  PROFILE_PHOTO = 'PROFILE_PHOTO',
}

export enum OutboxStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}
